### ISSUE TITLE
Doc: Documentating actions on merge

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/OpenScPCA-analysis#118]
Write steps the researchers should take to document any actions/events that occur during merging a PR

**Relevant Journey  Maps**
- [Merge PR](https://www.figma.com/file/qjvNYWo8Tkv6HZ5yd6i9oE/OpenScPCA-Journey-Mapping?type=whiteboard&node-id=248-4325&t=hKLukrMkKXtBBbIm-11)

**Comment by sjspielman** [comment]
The main activity to do here will be to sync your fork, and we already have this noted here:

https://github.com/AlexsLemonade/OpenScPCA-analysis/blob/61972d8f636d186836f567a5472fdece4eb4e983/docs/contributing-to-analyses/pr-review-and-merge/index.md?plain=1#L38-L44

Therefore, we can consider this issue all set.
