### ISSUE TITLE
Directory: Setting up

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/OpenScPCA-analysis#120]
This is a directory. In `index.md`:

Outline steps to setup locally
- Getting a Github client (#10)
- Fork (#34)
- Clone (#12) 
- Setup environment (#13)

Link to appropriate detailed docs.

**Comment by jaclyn-taroni** [comment]
@sjspielman Do you think this should be closed at this point? I do think it's outlived its usefulness as an Epic, but I'm not sure if the `index.md` described still needs to be updated.

**Comment by sjspielman** [comment]
My understanding is that we actually aren't intended to have an `index.md` file here at all, so indeed this issue can be closed. @dvenprasad, can you confirm?

**Comment by dvenprasad** [comment]
This can be closed. This [page](https://openscpca.readthedocs.io/en/latest/technical-setup/) covers what this ticket is outlining and it is in the correct place.
