### ISSUE TITLE
Doc: Setting up Docker

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/OpenScPCA-analysis#124]
Write docs with instructions to setup docker

**Relevant Journey Maps**
- [Acquire existing docker image for a module (Locally)](https://www.figma.com/file/qjvNYWo8Tkv6HZ5yd6i9oE/OpenScPCA-Journey-Mapping?type=whiteboard&node-id=371-2651&t=hKLukrMkKXtBBbIm-11)
- [Setup repo locally](https://www.figma.com/file/qjvNYWo8Tkv6HZ5yd6i9oE/OpenScPCA-Journey-Mapping?type=whiteboard&node-id=0-1&t=K73mzylOLxkPQstM-11)

**Comment by sjspielman** [comment]
We have docs explaining how to install docker (https://openscpca.readthedocs.io/en/latest/software-platforms/docker/) and how to find/modify module Dockerfiles (https://openscpca.readthedocs.io/en/latest/software-platforms/docker/docker-images/).
