### ISSUE TITLE
Update R/RStudio windows instructions for WSL

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenScPCA-analysis#253]
We need to update R/RStudio install instructions for windows users. 
After they install WSL, they will need to install all the R things _on the Ubuntu side_:

- install linux R
- install RStudio _Server_ (since they can't use Desktop)
  -  also explain how to launch server

Somewhere towards the top, remind them that we are recommending this because OpenScPCA's supported operating systems are mac and linux, not windows, so this is how they can use windows in a way where we can help them the most. They can still their regular Windows setup but may not be able to do all the things in openscpca.

**Comment by sjspielman** [comment]
Update: 

I have successfully installed R and tidyverse, BiocManager, and SingleCellExperiment packages on WSL2 using this code adapted from  https://cloud.r-project.org/bin/linux/ubuntu/:

```
# install two helper packages we need
sudo apt install --no-install-recommends software-properties-common dirmngr

# add the signing key (by Michael Rutter) for these repos
# To verify key, run gpg --show-keys /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc 
# Fingerprint: E298A3A825C0D65DFD57CBB651716619E084DAB9
wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc

# add the R 4.0 repo from CRAN -- adjust 'focal' to 'groovy' or 'bionic' as needed
sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"

# install r. r-base-dev is needed for building packages
sudo apt install --no-install-recommends r-base r-base-dev

# install some other things that r packages will need - much of this list were libraries that got flagged as missing during tidyverse install
sudo apt install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype-6-dev libpng-dev libtiff5-dev libjpeg-dev
```

However, I am not able to install RStudio Server and I'm a bit stuck doing so. I began by following `Step 3` here: https://posit.co/download/rstudio-server/
Installing `gdebi-core` and `wget`'ing the installer were fine, but that I was unable to actually install RStudio Server. This is because RStudio Server requires `libssl1.0.0|libssl1.0.2|libssl1.1`, but in Ubuntu 22.04, these are all deprecated and can't be obtained as far as I can tell; that library version now is `libssl3`. This appears to be a known problem, and has been so without much movement, for 2 years: https://forum.posit.co/t/dependency-error-when-installing-rstudio-on-ubuntu-22-04-with-libssl/135397/2. I haven't had much luck with stackoverflow, and I'm very hesitant to even consider suggesting one of the RStudio daily builds (especially a build from 2022 as linked in that posit forum post). 

My current thought is maybe to just recommend VS Code, and provide a couple extension suggestions for R, for WSL2? Any other ideas of what I could try here that will not take an unreasonable amount of time?
CC @jaclyn-taroni @jashapiro

**Comment by jashapiro** [comment]
That thread implies to me that it has been fixed, as that daily is quite old. I was able to install RStudio on Ubuntu Jammy just last week on our server. What is the exact error you saw?

I am currently doing an install in a docker image to see if I can reproduce your error.

**Comment by jashapiro** [comment]
Okay, I am getting the same error in a docker image. Will think about it for a sec and compare what we have on the server

**Comment by jashapiro** [comment]
Oh, my error was not updating the page to select "jammy". Was that also yours? The correct download should be:
`wget https://download2.rstudio.org/server/jammy/amd64/rstudio-server-2023.12.1-402-amd64.deb` or more generally (from the Rocker project): `wget https://rstudio.org/download/latest/stable/server/jammy/rstudio-server-latest-amd64.deb`

**Comment by sjspielman** [comment]
We're up and running! 

--- 

Next steps: I'm somewhat tempted to put much (all?) of these installation steps into a shell script that they can just call rather than tons of copy and pasting. Would love to hear if someone has strong objections to this!

**Comment by jaclyn-taroni** [comment]
Would you expect that they have a copy of the repository locally at this point in the set-up process? If the answer is no or maybe—since this installation step is fairly independent—then I'm not sure a script is better than copying and pasting. (Side note: Can't you copy and paste everything all at once?) Also, there is very limited potential for path problems when copying and pasting.

**Comment by sjspielman** [comment]
> If the answer is no or maybe—since this installation step is fairly independent—then I'm not sure a script is better than copying and pasting.

I guess it is maybe - while I would expect them to have the repo given that these instructions are the last page in setup, but there is of course no requirement to have the repo yet for this independent installation.

> (Side note: Can't you copy and paste everything all at once?) 

Ok you've convinced me, just one big copy/paste chunk seems ok for the R installation! There are only 2 RStudio lines (wget the installer and install the installer), but it turns out that installing the server also ends up _launching_ the server, so I think I'd prefer those to be separate calls.

**Comment by jashapiro** [comment]
Another note: I think you can skip installing `gdebi` and just use `apt install ./rstudio-server-latest-amd64.deb`

**Comment by sjspielman** [comment]
> Another note: I think you can skip installing gdebi and just use apt install ./rstudio-server-latest-amd64.deb

Just checked - yup!!

**Comment by jashapiro** [comment]
One more thought: We might have them set CRAN to `https://p3m.dev/cran/__linux__/jammy/latest` to get binary installs of R packages for much faster installation (and maybe a few fewer dependencies)

**Comment by sjspielman** [comment]
closed by https://github.com/AlexsLemonade/OpenScPCA-analysis/pull/372
