### ISSUE TITLE
Doc: Working with snapshots

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenScPCA-analysis#262]
This will go under the Lightsail for Research directory (#258) and cover working with snapshots. I would expect it to link out very heavily to AWS Lightsail for Research docs on snapshots, but make some recommendations about frequency, naming, etc.

**Comment by sjspielman** [comment]
Let's fill in this stub link while writing these docs - https://github.com/AlexsLemonade/OpenScPCA-analysis/issues/145#issuecomment-2037880050
