### ISSUE TITLE
Idea: Modularize and programmatically concatenate docs together to avoid maintaining duplicate sections

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenScPCA-analysis#37]
#### Context

We have to explain to participants how to get set up to contribute in at least two main contexts: 1. on Lightsail for Research and 2. on their own computer. (In the future, perhaps there will be some basic set of HPCs "gotchas" we run into that we cover!) Many of those steps would be shared. For example, cloning the repository, setting up the minimal conda environment, and setting up pre-commit will be required in both settings. However, I don't expect the steps to be that materially different.

#### Problem or idea

It might be _most convenient_ for people reading the docs if they didn't have to skip around to different sections – and we really want to optimize for making onboarding as frictionless as possible. But if we maintain two different sections where we write about pre-commit and discover that something is unclear, we could be in a situation where we only remember to update one instance of those docs. 

So my idea is to look into ways to reference common sections (e.g., setting up pre-commit) that live in standalone Markdown documents in larger sections (e.g., "Getting Started on Lightsail for Research"). You could probably do this in its simplest form by concatenating things with Pandoc in a GitHub Action.

#### Next steps

Tagging @dvenprasad and @sjspielman to weigh in. If skipping around is unlikely to happen, given where the IA is headed, or if it is not going to be a big deal, it's probably overengineering, and we don't have to invest any effort into looking into this. Part of the issue is that we haven't mapped out Lightsail for Research yet, so maybe we should wait and see.

**Comment by sjspielman** [comment]
At this point with the vast majority of docs written, I think it's unlikely we will need to worry about this so I'm going to close this out as unplanned.
