### ISSUE TITLE
Docs idea: How to obtain a template notebook

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenScPCA-analysis#377]
...but this does make me think it might be helpful to add something to docs about how to download (either via GitHub or `wget`) the template notebook in case someone wants a template notebook more generally. 

_Originally posted by @sjspielman https://github.com/AlexsLemonade/OpenScPCA-analysis/pull/375#discussion_r1576211382_

---

We have both Rmd and Jupyter template notebooks that contributors may want to use, just not immediately when they create a module. We could consider adding docs about obtaining these files if/when you need them

**Comment by jaclyn-taroni** [comment]
They will already have them locally.

**Comment by sjspielman** [comment]
> They will already have them locally.

Wow. This...yeah. This is it. Still a little tired over here 😂.
