### ISSUE TITLE
Add analysis ignored files to top-level .gitignore

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenScPCA-analysis#379]
When contributors first create a new module but _before they `git add .gitignore`_, they can potentially add some no-go files (`scratch`, `results`, etc). 

I wonder if we want to add some of these analysis module specific files that we know need to be ignored into the top-level `.gitignore` file? Otherwise, I can foresee Problems™️ e.g. if contributors add/commit `results` before `.gitignore`. We could also consider adding something to docs to make sure they add/commit `.gitignore` first, but I don't think we can expect that everyone will see this instruction and/or remember this instruction when it comes time to actually start an analysis. I think adding to the overall `.gitignore` is therefore safer. 

Any other ideas, chime on in!

**Comment by jashapiro** [comment]
As long as they do not first _delete_ the `.gitignore` file, it should still be respected by `git`, right?

Followup: I just tested this with both GitKraken and `git` and that seems to be the case:

```
❯ git add analyses/tester/results/*
The following paths are ignored by one of your .gitignore files:
analyses/tester/results/testfile
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
```

**Comment by sjspielman** [comment]
Alright, we should be good then. If a contributor runs into a problem we can revisit.
