### ISSUE TITLE
LSfR docs: Stop the computer

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenScPCA-analysis#396]
It looks like we do not recommend anywhere that contributors formally stop their computers after a session. It's been my understanding (?) that we do want to make sure computers are stopped in between coding sessions to avoid extra charges. If I'm mistaken here please let me know, but otherwise we should include in the "Developing on LSfR" doc that they should stop the computer in between coding sessions.

**Comment by jaclyn-taroni** [comment]
The cost control rule stops the computer once it dips below a certain percentage of CPU utilization for a specified time (a maximum of 30 minutes). It certainly doesn't hurt to make this explicit, though.
