### ISSUE TITLE
Docs request: Downloading workflow results

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/OpenScPCA-analysis#428]
### What is the documentation improvement or update you wish to see?

In #426, I am adding a `download-results.py` script to allow downloading of results from the `openscpca-nf` workflow. While the basics of this functionality is documented in the script itself, the expected use cases and example invocations are not. 

We should cover where the results are stored on S3 and the default download locations, as well as some of the more relevant options, including the ability to download results filtered by project or sample (assuming that all that makes it past the review of #426 as implemented).

I am not sure exactly where this would go in the current structure, but we might have a general section about using one module's results in a secondary module. 

### Is there any additional context you would like to provide?

This documentation will likely be tied in with the description of the workflow described as part of https://github.com/AlexsLemonade/OpenScPCA-analysis/issues/399, so it may be helpful to plan these two additions together.

**Comment by sjspielman** [comment]
Notes from discussion @dvenprasad and I had for how to implement these docs: 

1. We're going to add a new page to the analysis modules section named something like (tbd..) `Working with analysis results` or `Using existing analysis results`. This doc will explain the usage of this script including where to find results once they have been download, as well as additional documentation needed to explain this
2. We're going to link this new page from the documenting your analysis docs

**Comment by sjspielman** [comment]
Noting to send to @jashapiro for review.
