### ISSUE TITLE
Create a module-specific Docker builder workflow template in `templates/workflows`

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenScPCA-analysis#443]
Each analysis module will have its own Docker image. We want to build and push that image anytime relevant files are altered (e.g., `analyses/{module name}/Dockerfile`, relevant lock files) to the `openscpca` public registry on ECR. We will use the module name as the image name. 

To facilitate setting this up for each module, we should create a template in `templates/workflows` that builds and pushes the images to ECR.

It should have the following features:

- The `on:` information is commented out to start, but we likely want to include:
  - Changes in PRs to `main` in the module  `Dockerfile` and the relevant files if using `renv` or `conda` trigger building
  - `workflow_dispatch`
  - `workflow_call` (not sure if we'll end up using this one, but it didn't seem like there's harm in including it!)
- We'll log in using `aws-actions/configure-aws-credentials` and `aws-actions/amazon-ecr-login` (see: https://github.com/AlexsLemonade/OpenScPCA-analysis/blob/main/.github/workflows/docker-image.yml)
- Tag images using `latest` and something like `${{ github.run_number }}` or `${{ github.sha }}`
- We should only _push_ to ECR upon merge. My current thinking is that we can use dependencies between jobs for this!
  - We'll need to handle creating a repository if it doesn't exist yet. As an example:
    ```sh
    aws ecr-public create-repository --repository-name {repository} || echo "{repository} already exists!"
    ``` 

It makes sense to work through these ideas with `simulate-sce` as an example! We may want to look into Docker actions for some of these steps.

**Comment by jashapiro** [comment]
closed by #474
