### ISSUE TITLE
Add GitHub Action workflow creation as part of `create-analysis-module.py`

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/OpenScPCA-analysis#444]
Blocked by #443.

We already have two workflow templates in `templates/workflows`. We are adding one for building and pushing Docker with #443. We should create workflows for a module when someone creates a module via the `create-analysis-module.py` script.

An expected follow-up to this issue is documenting this new capability in `docs/`.

**Comment by sjspielman** [comment]
The module creation script now creates the workflow, and this behavior has been documented. 

Going to leave this issue open for now given this active PR: https://github.com/AlexsLemonade/OpenScPCA-analysis/pull/459

**Comment by jashapiro** [comment]
Closed with #474
