### ISSUE TITLE
Update conda docs: create an environment.yml file

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenScPCA-analysis#449]
While working with conda environments, I came across a situation that we did not document on the software page (note that we expect this page to change too, see https://github.com/AlexsLemonade/OpenScPCA-admin/issues/194).

Currently, we only document creating a conda lock file from an existing `environment.yml`. If someone wants to add a conda environment to a module _after the module has been created_, we currently direct contributors to run the environment creation command from the repo root. In this case, there is no existing `environment.yml` file in the module to run conda lock on. We therefore need to document exporting an environment to be able to create a conda lock file from it*.

**edit** - looks like we never actually introduce `export` even to update an existing environment, so there may be more to think about here.

**Comment by sjspielman** [comment]
Specifically: https://docs.google.com/presentation/d/1RsDIR2wtfIkdwg6FDJghlZl9qrwuICmupMrDNTKOAjw/edit#slide=id.g2d16ff673eb_0_15

**Comment by jashapiro** [comment]
We should probably suggest copying and modifying the template file... We don't talk about `export` in part because it doesn't play that well with `conda-lock` in that it will remove the `platforms:` section (I think) and we do want to keep that. It was something I was a bit torn about, tbh.

**Comment by sjspielman** [comment]
> We should probably suggest copying and modifying the template file.

I actually just went to do this after indeed observing `export` play poorly with `conda-lock`! It still doesn't like `jq` (which I have a memory of encountering previously!), so I ended up removing that version tag in the module's environment file.

**Comment by sjspielman** [comment]
> it doesn't play that well with conda-lock in that it will remove the platforms: section (I think) and we do want to keep that.

There is no `platforms:` section in the repo root `environment.yml` file - is that what you were referring to?

**Comment by jashapiro** [comment]
> > We should probably suggest copying and modifying the template file.
> 
> I actually just went to do this after indeed observing `export` play poorly with `conda-lock`! It still doesn't like `jq` (which I have a memory of encountering previously!), so I ended up removing that version tag in the module's environment file.

`jq` is a problem only on windows, which is in the conda-lock default platform list. That is why we need a `platforms` directive.

**Comment by sjspielman** [comment]
Re-considering this, I think the docs we need probably are there, but they are just a bit tricky to find because the current docs page contains so much information. We're planning to update some of that shortly, so the confusion I had when writing this issue may resolve itself after the rearrangement.

**Comment by sjspielman** [comment]
Closed by #578
