### ISSUE TITLE
Making changes to existing analysis modules

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/OpenScPCA-analysis#51]
~~This is to be tucked under (#50)~~. Write instructions for user to modify an existing analysis. Include reminders to comment their code (link to details in #52)

**Relevant Journey Maps**
[Notify disagreement and propose new solution](https://www.figma.com/file/qjvNYWo8Tkv6HZ5yd6i9oE/OpenScPCA-Journey-Mapping?type=whiteboard&node-id=255-4328&t=ElcuB4UWylzhAGj6-11)

**Comment by sjspielman** [comment]
This is effectively the same scope as #52, so I'm closing this in favor of just #52.
