### ISSUE TITLE
Documenting your updates (from modifying analysis)

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/OpenScPCA-analysis#52]
Write docs for users to know what they need to document like the analysis README, Docker file (link to docker section for detailed instructions), code comments.

**Relevant Journey Maps**
[Notify disagreement and propose new solution](https://www.figma.com/file/qjvNYWo8Tkv6HZ5yd6i9oE/OpenScPCA-Journey-Mapping?type=whiteboard&node-id=255-4328&t=ElcuB4UWylzhAGj6-11)

**Comment by sjspielman** [comment]
As part of this, do tasks originally laid out in #51:
>  Write instructions for user to modify an existing analysis. Include reminders to comment their code (link to details in #52)
> 
> **Relevant Journey Maps** [Notify disagreement and propose new solution](https://www.figma.com/file/qjvNYWo8Tkv6HZ5yd6i9oE/OpenScPCA-Journey-Mapping?type=whiteboard&node-id=255-4328&t=ElcuB4UWylzhAGj6-11)
