### ISSUE TITLE
Update data download script: symlink treatment

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenScPCA-analysis#530]
Related to #523 

We'd like to update the `download-data.py` script to have an option where users can swap symlinks between test and release without having to re-download all the data.  

To implement this, we discussed an argument `--update-symlinks <test/current/a given release date>` to toggle the symlink. This argument should check to see if the data of interest exists locally and give some kind of informative message about the swap, but should not attempt to download fresh. We should write a small function to do the symlink toggling.

**Comment by jashapiro** [comment]
Just noting that the relevant current code is at https://github.com/AlexsLemonade/OpenScPCA-analysis/blob/36314e4dd8730dca4820c1502c8d18898f687d48/download-data.py#L245C1-L252C69

You will probably want to refactor this out into the function as described above that can be called either in its current location or when using the `--update-symlinks` function.
