### ISSUE TITLE
Doc: Examples of review comments

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/OpenScPCA-analysis#56]
Write a doc containing examples of the types of comments contributors can expect to receive and if applicable why. Example, if they receive a comment about code style - we want to maintain readability etc. etc. 

**Relevant Journey Maps**
[Respond to review](https://www.figma.com/file/qjvNYWo8Tkv6HZ5yd6i9oE/OpenScPCA-Journey-Mapping?type=whiteboard&node-id=371-3001&t=ElcuB4UWylzhAGj6-11)

**Comment by allyhawkins** [comment]
Note that we should update the commented out link in the index for this directory once this file exists, see #371.

**Comment by sjspielman** [comment]
@allyhawkins I've removed you and assigned myself here since I apparently have done all the work in #381 🙃

**Comment by sjspielman** [comment]
Closed with #381
