### ISSUE TITLE
Error in downloading test data using download-data.py

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/OpenScPCA-analysis#560]
### Describe the bug

In attempting to download test data in the GHA for running the `cell-type-ewings` module, I get an error that it can't update the symlink because no data is downloaded. 

<img width="450" alt="Screenshot 2024-07-03 at 8 56 45 AM" src="https://github.com/AlexsLemonade/OpenScPCA-analysis/assets/54039191/c07a2021-41ea-44d1-89a3-a37d4ef9f1d5">

### Steps to reproduce

This is the command that is being run `./download-data.py --test-data --format "sce,anndata" --samples SCPCS000490`. 

Based on the description of arguments in the script I should still be able to download test data this way, but that doesn't appear to be the case.

### Consequences of the bug

GHA is currently failing and I cannot download test data for the first time.

**Comment by jashapiro** [comment]
@allyhawkins Can you test again? Should be fixed.

**Comment by allyhawkins** [comment]
> @allyhawkins Can you test again? Should be fixed.

Appears to be working, thank you!
