### ISSUE TITLE
Consider options to reduce test times

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/OpenScPCA-analysis#631]
When making modifications to the `detect-doublets` module, I became acutely aware of how long that module is taking to test. 

This is mostly my fault, as I requested that it be run on _all_ test data during an early review. I stand by that decision, as my memory is that it did discover some edge cases that would have otherwise not been caught. However, at this stage with that module largely "mature" module, that level of testing seems like a bit of overkill.

I think the best option is to select a "representative" subset of samples that span projects, with special focus on cases that have caused errors in the past or are likely to cause errors in the future (looking at you, multiplexed data!). 

We might retain an option to run on all data for periodic testing runs. In other words, PRs could run a shorter check, with monthly checks using the full data (simulated) sets. This seems to me to be a good compromise between speed of development and catching edge cases. 

What do others think? 

Tagging folks: @allyhawkins @jaclyn-taroni @sjspielman

**Comment by sjspielman** [comment]
> I think the best option is to select a "representative" subset of samples that span projects, with special focus on cases that have caused errors in the past or are likely to cause errors in the future (looking at you, multiplexed data!).

This seems like a good idea to me too

**Comment by allyhawkins** [comment]
I think this sounds good. I especially like the idea that PRs run on smaller datasets while the monthly checks could be the full data set.

**Comment by jaclyn-taroni** [comment]
Sounds good.

**Comment by jashapiro** [comment]
@sjspielman Can you take the first crack at this with `detect-doublets`? Alternatively, do you have a list of samples you could suggest?

**Comment by sjspielman** [comment]
I don't really have a set of samples to test other than the 1 small dataset I know of which kept interrupting doublets code, but still happy to take a crack at this!
I wonder if we would want finding these datasets to be a module in and of itself?

**Comment by jashapiro** [comment]
> I don't really have a set of samples to test other than the 1 small dataset I know of which kept interrupting doublets code, but still happy to take a crack at this! I wonder if we would want finding these datasets to be a module in and of itself?

I don't think we need a module. For now maybe just pick one from each project, but be sure to include at least one of the samples that failed. If/when we get other failures from full runs, we can add those samples, perhaps.

**Comment by sjspielman** [comment]
I went ahead and tried running doublets over each the smallest (fewest number of cells) test processed library for each project, including some which had previously failed. All ran through without errors, so seems like as good a place as any to start!

```
SCPCP000001/SCPCS000018/SCPCL000018_processed.rds
SCPCP000002/SCPCS000030/SCPCL000030_processed.rds
SCPCP000003/SCPCS000057/SCPCL000713_processed.rds
SCPCP000004/SCPCS000696/SCPCL001058_processed.rds
SCPCP000005/SCPCS000293/SCPCL000519_processed.rds
SCPCP000006/SCPCS000178/SCPCL000215_processed.rds
SCPCP000007/SCPCS000225/SCPCL000299_processed.rds
SCPCP000008/SCPCS000369/SCPCL000640_processed.rds
SCPCP000009/SCPCS000145_SCPCS000146_SCPCS000147_SCPCS000148/SCPCL000545_processed.rds
SCPCP000010/SCPCS000404/SCPCL000675_processed.rds
SCPCP000011/SCPCS000435/SCPCL000756_processed.rds
SCPCP000012/SCPCS000725/SCPCL001087_processed.rds
SCPCP000013/SCPCS000738/SCPCL001100_processed.rds
SCPCP000014/SCPCS000518/SCPCL000850_processed.rds
SCPCP000015/SCPCS000749/SCPCL001111_processed.rds
SCPCP000016/SCPCS000504/SCPCL000836_processed.rds
SCPCP000017/SCPCS000608/SCPCL000936_processed.rds
SCPCP000020/SCPCS000618/SCPCL000946_processed.rds
SCPCP000021/SCPCS000636/SCPCL000964_processed.rds
SCPCP000023/SCPCS000773/SCPCL001135_processed.rds
```

**Comment by jashapiro** [comment]
The number of cells shouldn't matter in general as the test libraries all have the same number of cells, except in the case where there are very few cells (<100).

**Comment by sjspielman** [comment]
> except in the case where there are very few cells (<100).

This is where doublets failures are going to happen, hence the selection strategy to make sure I got those

**Comment by jashapiro** [comment]
> > except in the case where there are very few cells (<100).
> 
> This is where doublets failures are going to happen, hence the selection strategy to make sure I got those

Yes, I understand, but there could be failures for other reasons as well. My point is just that for many of the projects, the smallest set may not matter at all, so I don't think you need to pick all of the projects based on that. As long as we have some data sets that are small, the rest can be picked for other (or random) reasons.
