### ISSUE TITLE
Fix docs spacing

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenScPCA-analysis#700]
Just noticed that these bullets need to be tabbed in more (4 spaces, not 2): https://github.com/AlexsLemonade/OpenScPCA-analysis/blob/559d739f49dfcfc48528b22f60c2d871b02ab0b9/docs/contributing-to-analyses/analysis-modules/documenting-analysis.md?plain=1#L12-L13

**Comment by jashapiro** [comment]
YU so strict, mkdocs?
