### ISSUE TITLE
Docs: Running a docker image

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/OpenScPCA-analysis#75]
Write docs with instructions to run a docker image

**Comment by sjspielman** [comment]
Similar to #78, these docs are nice to have, but not quite as relevant until we have a critical mass of pushed docker images.

**Comment by sjspielman** [comment]
Noting that this should involve instructions for building and/or pulling an image, and running an analysis module from a container of that image.

**Comment by sjspielman** [comment]
Closing in favor of #496
