### ISSUE TITLE
Docs: Making changes to an existing dockerfile

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/OpenScPCA-analysis#77]
write docs with instructions to modify an existing dockerfile. Include a reminder to follow standards for dockerfile

**Comment by sjspielman** [comment]
We should consider adding this content to the current page on Docker images. Since this may not be something most (non-advanced) contributors will be doing, I don't think this rises to the level of its own page.

**Comment by sjspielman** [comment]
Closing in favor of #497
