### ISSUE TITLE
Annotation (label transfer) exploration for SCPCP000006

### ISSUE THREAD

**Issue by maud-p** [AlexsLemonade/OpenScPCA-analysis#774]
### If you are filing this issue based on a specific GitHub Discussion, please link to the relevant Discussion.

This PR is following the discussion from the PR#750, especially:
https://github.com/AlexsLemonade/OpenScPCA-analysis/pull/750#pullrequestreview-2310191830

### Describe the goals of the changes to the analysis module.

In this PR, I am adding one notebook in `/notebook/04_annotation_Across_Samples_exploration.Rmd` to explore the annotations and label transfers for all of the samples in SCPCP000006.

We integrated all the samples from SCPCP000006 to have a rapid and global view of label transfer. 
Please note that the integration is not the aim of this PR, this is just a way to display better genes and features. 

In order to explore the label transfer results, we look into some marker genes, table and percentages of cells in each annotation groups (from label transfers).

### What will your pull request contain?

One notebook that explores for all samples at once clustering and label transfer results.

### Will you require additional software beyond what is already in the analysis module?

no

### Will you require different computational resources beyond what the analysis module already uses?

no

### If known, when do you expect to file the pull request?

Today or tomorrow (European time)

**Comment by sjspielman** [comment]
This notebook was completed.
