### ISSUE TITLE
Docs: Getting access to docker image

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/OpenScPCA-analysis#78]
Write instructions to access a docker image

I'm not sure if we need this, the docker file in the analysis folder?

**Comment by sjspielman** [comment]
At this point, this issue scope would entail how to find Docker images after they have been pushed to the registry. This strikes me as more of a "nice to have" doc, but not one that is strictly critical at this project stage. Once we have more docker images pushed, it will become more important.

**Comment by sjspielman** [comment]
Closing in favor or #496
