### ISSUE TITLE
Anchor transfer for Wilms tumor annotation (SCPCP000014) 

### ISSUE THREAD

**Issue by JingxuanChen7** [AlexsLemonade/OpenScPCA-analysis#782]
### If you are filing this issue based on a specific GitHub Discussion, please link to the relevant Discussion.

https://github.com/AlexsLemonade/OpenScPCA-analysis/discussions/628

### Describe the goals of the changes to the analysis module.

The goal here is to conduct anchor transfer on Wilm tumor dataset (SCPCP000014), so that we could have an overview of the cell type components in each sample.

More specifically, it will contain following parts:
- Prepare a Seurat object for fetal kidney atlas (https://www.kidneycellatlas.org/fetal-kidney-global), which includes two levels of annotation: `compartment` and `celltype`.
- Conduct anchor transfer at `compartment` level.
- Conduct anchor transfer at `celltype` level.

I will also make slight modifications on the preprocessing functions filed in my first PR (https://github.com/AlexsLemonade/OpenScPCA-analysis/pull/764):
- Starting from raw count and adding the Seurat `logNormalize` function back during pre-processing. If the normalization method is not consistent between reference and query object, too few numbers of anchors would be identified.
- Remove genes with unknown gene symbols.

### What will your pull request contain?

This PR would contain code & doc to run anchor transfer, and documentation for corresponding results.

### Will you require additional software beyond what is already in the analysis module?

I will keep using R. Modification on packages would reflect in `renv.lock` file.

### Will you require different computational resources beyond what the analysis module already uses?

 Standard-4XL virtual computer (i.e, 16 cpus and 32 GB RAM) on Lightsail.

### If known, when do you expect to file the pull request?

~Early October

**Comment by jaclyn-taroni** [comment]
Hi @JingxuanChen7, I just wanted to point out that the other Wilms tumor cell typing module ([`cell-type-wilms-tumor-06`](https://github.com/AlexsLemonade/OpenScPCA-analysis/tree/main/analyses/cell-type-wilms-tumor-06)) is also using fetal atlases for transfer in case taking a look at that analysis would be helpful to you!

**Comment by JingxuanChen7** [comment]
Dear @jaclyn-taroni , thanks for pointing out this similar analysis! 

And yes, the basic idea of the anchor transfer is identical, with some differences in the actual tools we applied (standard seurat pre-processing workflow vs. SCTransform, Seurat `FindTransferAnchors` vs. Azimuth). I'm not sure how these differences would affect the results. But I think it's worth trying to add alternative options in my workflow in the future, probably in another PR.
