### ISSUE TITLE
pre-commit GHA clone is timing out

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenScPCA-analysis#818]
> We seem to be timing out on cloning the repo. This could be a more significant problem than just this PR: There is a time limit of 30s for cloning and we seem to be taking ~25 seconds in other PRs, meaning we are probably quite close to the repo size limit for the service.

_Originally posted by @jashapiro in https://github.com/AlexsLemonade/OpenScPCA-analysis/issues/813#issuecomment-2416957428_

**Comment by jashapiro** [comment]
Closing in favor of #819
