### ISSUE TITLE
First draft of annotations for SCPCP000006

### ISSUE THREAD

**Issue by maud-p** [AlexsLemonade/OpenScPCA-analysis#839]
### Describe the goals of the changes to the analysis module.

In the next PR, I would like to write a notebook that will provide the first annotations for the Wilms tumor dataset SCPCP000006.

The proposed annotation will be base on the combination of:
- the label transfer fron the fetal kidney reference (Stewart et al.), in particular the `fetal_kidney_predicted.compartment` and `fetal_kidney:predicted.cell_type`, as well as the `mapping.score` for each compartment,
- the predicted CNV calculated using intra-sample endothelial and immune cells (`--reference both`) as normal reference

We will then use some of the [markers genes](https://github.com/AlexsLemonade/OpenScPCA-analysis/tree/main/analyses/cell-type-wilms-tumor-06#the-table-celltype_metadatacsv-contains-the-following-column-and-information) to validate visually the annotations.

The analysis can be summarized as the following:

* Where `cnv.thr` and `map.thr` need to be discussed.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/MAUD~1.PLA/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/MAUD~1.PLA/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

first   level annotation | second level   annotation | selection of   the cells | marker genes   for validation | cnv validation
-- | -- | -- | -- | --
normal | endothelial | compartment == "endothelium"     & mapping_score > map.thr     & cnv_score < cnv.thr | WVF | no   cnv
normal | immune | compartment == "immune"     & mapping_score > map.thr     & cnv_score < cnv.thr | PTPRC, CD163, CD68 | no cnv
normal | kidney | cell_type %in% c("kidney cell",   "kidney epithelial", "podocyte")     & mapping_score > map.thr     & cnv_score < cnv.thr | CDH1, PODXL, LTL | no cnv
normal | stroma | compartment == "stroma"     & mapping_score > map.thr     & cnv_score < cnv.thr | VIM | no cnv
cancer | stroma | compartment == "stroma"     & cnv_score > cnv.thr | VIM | proportion_cnv_chr     -1     -4     -11     -16     -17     -18
cancer | blastema | compartment ==   "fetal_nephron"     & cell_type == "mesenchymal cell"     & cnv_score > cnv.thr | CITED1 | proportion_cnv_chr     -1     -4     -11     -16     -17     -18
cancer | epithelial | compartment ==   "fetal_nephron"     & cell_type != "mesenchymal cell"     & cnv_score > cnv.thr | CDH1 | proportion_cnv_chr     -1     -4     -11     -16     -17     -18
unknown | - | the rest of the cells | - | proportion_cnv_chr     -1     -4     -11     -16     -17     -18

</body>

</html>

### What will your pull request contain?

The PR will contain a `notebook`, extracting data for each of the sample such as done in [`04_annotation_Across_Samples_exploration.Rmd`](https://github.com/AlexsLemonade/OpenScPCA-analysis/blob/main/analyses/cell-type-wilms-tumor-06/notebook/04_annotation_Across_Samples_exploration.Rmd) for the `cell_type_df`.

We will try to visualize the data using `umap` reductions (DimPlot and FeaturesPlot) and heatmap of expression.

### If known, when do you expect to file the pull request?

Monday 28/10 or Tuesday 29/10 hopefully

**Comment by sjspielman** [comment]
Hi @maud-p, as part of this incoming PR, can you please also have a look through all of the README files in your analysis module and make sure they are up-to-date for the current analysis status? I think they are in fairly good shape, but this is a great time to check. Thanks!!

**Comment by sjspielman** [comment]
These annotations were completed in #844.
