### ISSUE TITLE
Move rOpenScPCA into new repo

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenScPCA-analysis#854]
We have written (and will continue to develop!) an R package called `rOpenScPCA` which is currently stored in the `packages` directory. Unfortunately, even though this package is in a subdirectory, installing packages from GitHub will _always_ download the whole repo, and this repo is already fairly big and will continue growing.

Therefore, we're going to create a new repository `AlexsLemonade/rOpenScPCA` that will hold this package moving forward. This issue tracks:

- Creating new repo with the current version of the package
  - This should include a testing workflow  
- Removing the `packages` directory from this repo and updating current code to reflect this change:
  - Update documentation/instructions in `hello-clusters`
  - Update `renv` environment in the `cell-type-nonETP-ALL-03` (edit) *and `cell-type-ETP-ALL-03` module to install package from the correct remote
  - Remove the testing GHA workflow

**Comment by jaclyn-taroni** [comment]
Both `cell-type-nonETP-ALL-03` and `cell-type-ETP-ALL-03` will need to be updated once  #847 goes in.
