### ISSUE TITLE
Use clustering functions from rOpenScPCA in `cell-type-ewings` module cluster report

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/OpenScPCA-analysis#878]
### If you are filing this issue based on a specific GitHub Discussion, please link to the relevant Discussion.

#292 

### Describe the goals of the changes to the analysis module.

In the cell typing module for Ewing samples (SCPCP000015), we have a [clustering report](https://github.com/AlexsLemonade/OpenScPCA-analysis/blob/main/analyses/cell-type-ewings/template_notebooks/clustering-workflow/01-clustering.Rmd) that we want to generate for all samples. Since this was written, some of the functions have moved to the new `rOpenScPCA` package. We should update that report to utilize those new functions. 

### What will your pull request contain?

Updates to the existing `01-clustering.Rmd` in the cluster workflow for Ewing's samples to use clustering functions from `rOpenScPCA`. 

### Will you require additional software beyond what is already in the analysis module?

I need to add the `rOpenScPCA` package to renv and docker file. That should happen in a separate PR before updating the code.

**Comment by allyhawkins** [comment]
Note that as part of this I am planning on adding in calculation of Leiden clusters with varying resolutions to the report. I'm going to use the same plots as far but will just update the faceting to include the Leiden results.

**Comment by jashapiro** [comment]
> Note that as part of this I am planning on adding in calculation of Leiden clusters with varying resolutions to the report. I'm going to use the same plots as far but will just update the faceting to include the Leiden results.

Just to note for this you will want to be sure to look at the `objective_function` parameter, as it has a *strong* effect on results.
