### ISSUE TITLE
Identify a tool to find related ontology IDs

### ISSUE THREAD

**Issue by allyhawkins** [AlexsLemonade/OpenScPCA-analysis#888]
### If you are filing this issue based on a specific GitHub Discussion, please link to the relevant Discussion.

#853 

### Describe the goals of the changes to the analysis module.

Before attempting to define a set of rules for consensus cell types, we should figure out what tools may be available to identify related ontology terms easily. 

### What will your pull request contain?

This probably won't be a PR, but I plan on looking into tool options and posting comments on this issue.

**Comment by jashapiro** [comment]
I guess I gave my thought in the wrong issue: https://github.com/AlexsLemonade/OpenScPCA-analysis/issues/886#issuecomment-2479683498

**Comment by allyhawkins** [comment]
After looking into some ideas on how to do this, I would agree that I think we want to move forward with [`OntologyX`](https://academic.oup.com/bioinformatics/article/33/7/1104/2843897). This package has a suite of packages including [ontologyIndex](https://cran.r-project.org/web/packages/ontologyIndex/vignettes/reading-ontologies.html) and [ontologySimilarity](https://cran.r-project.org/web/packages/ontologySimilarity/vignettes/ontologySimilarity-introduction.html) that I think could help us with this challenge. I was able to do the following things with the package: 

- Create an `ontologyIndex` from the `.obo` file for CL (downloaded from [OBO](https://obofoundry.org/ontology/cl.html)). I used the basic version of the file as the full version was unable to be processed by `ontologyIndex`. This object contains associated ancestors and descendants for each of the terms, which makes it easy to look up any terms that may be related to each other. 
- I then used the `ontologySimilarity` package to calculate the Lin between-term similarity between `CellAssign` and `SingleR` ontology IDs for a given cell. I think this could be a potentially useful metric to measure how similar terms are to each other and then we would need to figure out how to identify a threshold for saying the terms are the same vs. different. 
	- The way this metric is calculated is by first calculating how frequently each term in the ontology appears as an ancestor of other terms. 
	- All shared ancestors between the two terms being compared are identified 
	- The frequency of the shared ancestor that is the least frequent is normalized and reported as the similarity value 
	- The similarity value is on a 0-1 scale where 0 is the least similar and 1 is the most similar/exact match in IDs
- There are a variety of functions in `ontologyIndex` that can be used to identify shared ancestors and descendants that could be useful if we want to just try and create simple rules around how many shared ancestors terms have. 

I think a good first step is to take one of the samples where we know there are some shared cell types and some not shared cell types between SingleR/CellAssign and calculate this similarity index on all of the cells. We would then plot the distribution and validate that cells, where we expect them to be matches, have high similarity values and those that should not match have low similarity values. For example, I would expect a high similarity in the scenario where one method labels the cell as a T cell and the other method labels the cell as a CD4 T cell. But I would not expect cells to match where one is a T cell and the other labels the cell as a fibroblast. 

If we proceed with using this metric, we will need to come up with some sort of threshold that we can use to classify cells as sharing the label vs. not sharing the label. One thought I had was to do permutation testing where we randomly select ontology terms and get a distribution of the similarity index. Then we can test if the observed similarity index is significant compared to the null distribution of values. Those with significant values would then receive a consensus label. I believe this is the approach that is taken by `ontologySimilarity::get_sim_p()` but the documentation on that function is not super clear so we would need to look into it further. 

We will also need to figure out how to actually assign the label to cells that are classified as similar. I think we would want to take the closest shared ancestor and use that ontology ID. 

Just to note that I also looked at using [`ontoProc`](https://www.bioconductor.org/packages/devel/bioc/vignettes/ontoProc/inst/doc/ontoProc.html). This tool would help us build trees and show relationships between ID's, but it wasn't as easy to use as `ontologyX`. Also every google search led me back to `ontologyX`. 

I'm going to close this issue since I think the decision to use `OntologyX` is pretty straightforward and move any discussion about the actual approach to #889.
